# Generated by Django 2.1.1 on 2018-11-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181112_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', help_text='学员报名后，请改为真实姓名', max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
