# Generated by Django 2.1.1 on 2018-11-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181112_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='app01.ClassList', verbose_name='已报班级'),
        ),
    ]
