# Generated by Django 2.1.1 on 2018-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_classstudyrecord_student_studentstudyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudyrecord',
            name='has_homework',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='本节有作业'),
        ),
    ]
