# Generated by Django 2.2.3 on 2019-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_campuses_classlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('qq', 'qq群'), ('referral', '内部转介绍'), ('website', '官方网站'), ('ads', '百度推广'), ('office_direct', '直接上门'), ('WoM', '口碑'), ('public_class', '公开课'), ('website', '编程go官网'), ('others', '其它')], default='qq', max_length=64, verbose_name='客户来源'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
