# Generated by Django 2.2.3 on 2019-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20190730_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='first.ClassList', verbose_name='已报班级'),
        ),
    ]
