# Generated by Django 2.2.3 on 2019-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20190801_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.CharField(blank=True, choices=[('full_time', '线下班'), ('online', '网络班'), ('weekend', '周末班')], default=1, max_length=64, verbose_name='班额及类型'),
        ),
    ]
