# Generated by Django 2.2.3 on 2019-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20190801_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.CharField(blank=True, choices=[('full_time', '线下班'), ('online', '网络班'), ('weekend', '周末班')], max_length=64, null=True, verbose_name='班额及类型'),
        ),
    ]
