# Generated by Django 2.2.3 on 2019-08-01 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_auto_20190801_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='department',
            name='count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.Department'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.CharField(blank=True, choices=[('full_time', '脱产班'), ('online', '网络班'), ('weekend', '周末班')], max_length=64, null=True, verbose_name='班额及类型'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.CharField(choices=[('Linux初级', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], max_length=64, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'pk': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_type',
            field=models.CharField(choices=[('full_time', '脱产班'), ('online', '网络班'), ('weekend', '周末班')], default='fulltime', max_length=64, verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Linux初级', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], max_length=23, null=True, verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', help_text='学员报名后，请改为真实姓名', max_length=32, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='class_type',
            field=models.CharField(blank=True, choices=[('full_time', '脱产班'), ('online', '网络班'), ('weekend', '周末班')], default='N/A', max_length=64, null=True, verbose_name='班级类型'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='course',
            field=models.CharField(blank=True, choices=[('Linux初级', 'Linux中高级'), ('PythonFullStack', 'Python高级全栈开发')], default='N/A', max_length=64, null=True, verbose_name='课程名'),
        ),
    ]
