# Generated by Django 2.2.3 on 2019-08-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20190801_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
