# Generated by Django 2.2.3 on 2019-08-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_auto_20190801_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='depart',
        ),
    ]
