# Generated by Django 2.2.4 on 2019-08-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20190804_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
