# Generated by Django 2.2.4 on 2019-08-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.IntegerField(choices=[(1, 'c'), (2, 'vip'), (3, 'svip')], default=1),
        ),
    ]
